PizzaStore/PizzaStore.MVC/Models/PizzaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using PizzaStore.Library;
using PizzaStore.Data;

namespace PizzaStore.MVC.Models
{
    public class PizzaViewModel
    {

        public int CrustID { get; set; }
        public Dictionary<int, string> Crusts { get; set; }

        public int SauceID { get; set; }
        public Dictionary<int, string> Sauces { get; set; }


        public IList<string> SelectedCheeses { get; set; }
        public IList<SelectListItem> AvailableCheeses { get; set; }


        public IList<string> SelectedToppings { get; set; }
        public IList<SelectListItem> AvailableToppings { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [StringLength(3, MinimumLength = 1)]
        public string PizzaQuantity { get; set; }

        public PizzaViewModel()
        {
            Crusts = GetCrusts();
            Sauces = GetSauces();

            SelectedCheeses = new List<string>();
            AvailableCheeses = GetCheeses();

            SelectedToppings = new List<string>();
            AvailableToppings = GetToppings();
        }

        private Dictionary<int, string> GetCrusts()
        {
            EfData ef = new EfData();
            List<Crust> crusts = ef.ReadCrusts();
            Dictionary<int, string> crustDict = new Dictionary<int, string>();
            foreach(var crust in crusts)
                crustDict[crust.CrustId] = crust.Crust1;
            return crustDict;
        }

        private Dictionary<int, string> GetSauces()
        {
            EfData ef = new EfData();
            List<Sauce> sauces = ef.ReadSauces();
            Dictionary<int, string> sauceDict = new Dictionary<int, string>();
            foreach (var sauce in sauces)
                sauceDict[sauce.SauceId] = sauce.Sauce1;
            return sauceDict;
        }


        private IList<SelectListItem> GetCheeses()
        {
            EfData ef = new EfData();
            List<Cheese> cheeseList = ef.ReadCheeses();

            List<SelectListItem> cheeseSelectList = new List<SelectListItem>();

            foreach(var cheese in cheeseList)
            {
                cheeseSelectList.Add(new SelectListItem { Text = cheese.Cheese1, Value = cheese.CheeseId.ToString() });
            }

            return cheeseSelectList;
        }

        public Pizza2 MakePizza()
        {
            Pizza2 pizza = new Pizza2();
            pizza.CrustId = CrustID;
            pizza.SauceId = SauceID;
            List<int> cheeseIDs = GetCheeseIDs();
            List<int> toppingIDs = GetToppingIDs();

            // Set Cheese1 and Cheese2
            if (cheeseIDs.Count == 0)
            {
                pizza.Cheese1 = null;
                pizza.Cheese2 = null;
            }
            else if (cheeseIDs.Count == 1)
            {
                pizza.Cheese1 = cheeseIDs[0];
                pizza.Cheese2 = null;
            }
            else if (cheeseIDs.Count == 2)
            {
                pizza.Cheese1 = cheeseIDs[0];
                pizza.Cheese2 = cheeseIDs[1];
            }

            // Set Topping1, Topping2, and Topping3
            if (toppingIDs.Count == 0)
            {
                pizza.Topping1 = null;
                pizza.Topping2 = null;
                pizza.Topping3 = null;
            }
            else if (toppingIDs.Count == 1)
            {
                pizza.Topping1 = toppingIDs[0];
                pizza.Topping2 = null;
                pizza.Topping3 = null;
            }
            else if (toppingIDs.Count == 2)
            {
                pizza.Topping1 = toppingIDs[0];
                pizza.Topping2 = toppingIDs[1];
                pizza.Topping3 = null;
            }
            else if (toppingIDs.Count == 3)
            {
                pizza.Topping1 = toppingIDs[0];
                pizza.Topping2 = toppingIDs[1];
                pizza.Topping3 = toppingIDs[2];
            }

            int q = 0;
            Int32.TryParse(PizzaQuantity, out q);
            pizza.Quantity = q;

            var ef = new EfData();
            pizza.TotalPizzaCost = 0;
            pizza.TotalPizzaCost += ef.GetCrustCost(pizza.CrustId);
            if(pizza.SauceId != null)
                pizza.TotalPizzaCost += ef.GetSauceCost(pizza.SauceId.Value);
            if (pizza.Cheese1 != null)
                pizza.TotalPizzaCost += ef.GetCheeseCost(pizza.Cheese1.Value);
            if (pizza.Cheese2 != null)
                pizza.TotalPizzaCost += ef.GetCheeseCost(pizza.Cheese2.Value);
            if (pizza.Topping1 != null)
                pizza.TotalPizzaCost += ef.GetToppingCost(pizza.Topping1.Value);
            if (pizza.Topping2 != null)
                pizza.TotalPizzaCost += ef.GetToppingCost(pizza.Topping2.Value);
            if (pizza.Topping3 != null)
                pizza.TotalPizzaCost += ef.GetToppingCost(pizza.Topping3.Value);

            pizza.ModifiedDate = DateTime.Now;

            return pizza;
        }

        public List<int> GetCheeseIDs()
        {
            List<int> cheeseIDs = new List<int>();
            foreach(var selectItem in SelectedCheeses)
                cheeseIDs.Add(Convert.ToInt32(selectItem));
            return cheeseIDs;
        }

        public List<int> GetToppingIDs()
        {
            List<int> toppingIDs = new List<int>();
            foreach (var selectItem in SelectedToppings)
                toppingIDs.Add(Convert.ToInt32(selectItem));
            return toppingIDs;
        }

        private IList<SelectListItem> GetToppings()
        {

            EfData ef = new EfData();
            List<Topping> toppingList = ef.ReadToppings();

            List<SelectListItem> toppingSelectList = new List<SelectListItem>();

            foreach (var topping in toppingList)
            {
                Console.WriteLine("Reading toppings from Efdata");
                toppingSelectList.Add(new SelectListItem { Text = topping.Topping1, Value = topping.ToppingId.ToString() });
            }

            return toppingSelectList;
        }
    }
}

PizzaStore/PizzaStore.MVC/Controllers/PizzaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PizzaStore.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using PizzaStore.Library;
using PizzaStore.Data;

namespace PizzaStore.MVC.Controllers
{
    public class PizzaController : Controller
    {
        [HttpGet] //This Action only supports Get Requests
        public IActionResult Index() //Any Action you Create you can respond to all http verbs
        {
            JsonHandler jh = new JsonHandler();
            if (HttpContext.Session.GetInt32("CostOfOrder") > jh.JsonObject.MAX_ORDER_TOTAL)
                ViewBag.PizzaProblem = string.Format("Order Exceeds ${0}. It was $", jh.JsonObject.MAX_ORDER_TOTAL) + HttpContext.Session.GetInt32("CostOfOrder").ToString();

            if (HttpContext.Session.GetInt32("InventoryProblem") == 1)
            {
                ViewBag.PizzaProblem = "Inventory insufficient for additional pizzas";
                HttpContext.Session.SetInt32("InventoryProblem", 0);
            }



            return View(new PizzaViewModel());
        }


        [HttpPost] //This does not work because client does not know which single parameter method to use
        public IActionResult Index(PizzaViewModel model) //actually only has to be an object that has the correct properties
        {
            int pizzaQuantity = 0;
            bool validQuantity = Int32.TryParse(model.PizzaQuantity, out pizzaQuantity);
            if(pizzaQuantity <= 0) { validQuantity = false; }
            if (ModelState.IsValid) // does same check as client side using [Required] annotations, this time they can't bypass it
            {
                if (model.SelectedCheeses.Count > 2 || model.SelectedToppings.Count > 3 || !validQuantity || model.CrustID == 0 || model.SauceID == 0)
                {
                    if (model.CrustID == 0)
                        ViewBag.PizzaProblem = "No Crust Chosen";
                    else if (model.SauceID == 0)
                        ViewBag.PizzaProblem = "No Sauce Chosen";
                    else if (model.SelectedCheeses.Count > 2)
                        ViewBag.PizzaProblem = "You can only have 2 cheeses";
                    else if (model.SelectedToppings.Count > 3)
                        ViewBag.PizzaProblem = "You can only have 3 Toppings";
                    else
                        ViewBag.PizzaProblem = "Invalid Pizza Quantity";

                    return View(new PizzaViewModel());
                }
            }

            var oh = HttpContext.Session.Get<OrderHandler>("OrderHandler");
            oh.Pizzas.Add(model.MakePizza());
            oh.TotalOrderValue += oh.Pizzas.Last().TotalPizzaCost.Value * oh.Pizzas.Last().Quantity;
            HttpContext.Session.Set<OrderHandler>("OrderHandler", oh);
            ViewBag.CompleteOrderProblem = "";

            return RedirectToAction("Index", "CompleteOrder");
        }
    }
}

PizzaStore/PizzaStore.MVC/Views/Pizza/Index.cshtml
@{
    ViewData["Title"] = "Add a Pizza Page";
}


@model PizzaStore.MVC.Models.PizzaViewModel

<header class="col-md-12">
    <h3>Add a Pizza to Your Order</h3>
    <p>@ViewBag.PizzaProblem</p>
</header>
<div class="col-md-12">
    <form asp-controller="Pizza" method="post">
        <h4>Crust</h4>
        <div class="form-group">
            @foreach (KeyValuePair<int, string> crust in Model.Crusts)
            {
                <div>
                    <label>@crust.Value</label>
                    <input asp-for="CrustID" type="radio" id="" value=@crust.Key />
                </div>
            }
        </div>
        <h4>Sauce</h4>
        <div class="form-group">
            @foreach (KeyValuePair<int, string> sauce in Model.Sauces)
            {
                <div>
                    <label>@sauce.Value</label>
                    <input asp-for="SauceID" type="radio" id="" value=@sauce.Key />
                </div>
            }
        </div>
        <h4>Cheeses (at most 2)</h4>
        <div class="form-group">
            <div class="container">
                @foreach (var item in Model.AvailableCheeses)
                {
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"
                                   name="SelectedCheeses"
                                   value="@item.Value" /> @item.Text
                            </label>
                        </div>
                }
            </div>
        </div>
        <h4>Toppings (at most 3)</h4>
        <div class="form-group">
            <div class="container">
                @foreach (var item in Model.AvailableToppings)
                {
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"
                                   name="SelectedToppings"
                                   value="@item.Value" /> @item.Text
                        </label>
                    </div>
                }
            </div>
        </div>
        <h4>How many of this pizza do you want?</h4>
        <div class="form-group">
            <div class="container">
                <label>Quantity of this Pizza: </label>
                <input asp-for="PizzaQuantity" value="1" />
            </div>
        </div>
        <button type="submit">Add Pizza(s) to Order</button>
    </form>
</div>